### ISSUE TITLE
Theme is Too Dark

### ISSUE THREAD

**Issue by Grip555** [Zerthox/ClearVision#116]
My V6 Sapphire theme won't work anymore, so I have to switch back to V5. However, the V5 theme is much darker than I would like it to be.

**Comment by BloodedWine** [comment]
V5 is no longer in development, and V6 isn't working right now due to a minor bug.

In fact, if you had looked at the [ClearVision Discord](https://discord.gg/HmVKer8) you would realize that the bug preventing V6 from working can easily be fixed.

Look at the Discord server before submitting bug reports, and please don't complain about an old theme being 'too dark'

Please close this issue to prevent wasting the dev's time.

**Comment by ShadoUrufu** [comment]
It's great that you found a solution and all that, but we should not have to join a discord group to sort through the various channels to find the fix.
